// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://uvtvgfdjwwgzttanpyzt.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InV2dHZnZmRqd3dnenR0YW5weXp0Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTM2MjA0NDIsImV4cCI6MjA2OTE5NjQ0Mn0.Ini7zALU1kT8mkdZj_SM06CYR8dNPN_pHCGG_zL3UAQ";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});